--!strict

--- ### Konbini.luau
---
--- a shelf of roblox-luau convenience modules \
--- [*view konbini on github*](https://github.com/00826/konbini)
return table.freeze{
	Color3 = require(script:WaitForChild("Color3"));
	Datastore = require(script:WaitForChild("Datastore"));
	Hook = require(script:WaitForChild("Hook"));
	Inputs = require(script:WaitForChild("Inputs"));
	Instance = require(script:WaitForChild("Instance"));
	Interface = require(script:WaitForChild("Interface"));
	Math = require(script:WaitForChild("Math"));
	Network = require(script:WaitForChild("Network"));
	Patronage = require(script:WaitForChild("Patronage"));
	Time = require(script:WaitForChild("Time"));
	Types = require(script:WaitForChild("Types"));
	Vector3 = require(script:WaitForChild("Vector3"));
}