--!strict

--- ### Konbini.luau
---
--- a shelf of roblox-luau convenience modules \
--- [*view konbini on github*](https://github.com/00826/konbini)
return table.freeze{
	Animation = require(script:WaitForChild("Animation"));
	Collisions = require(script:WaitForChild("Collisions"));
	Color3 = require(script:WaitForChild("Color3"));
	Couture = require(script:WaitForChild("Couture"));
	Datastore = require(script:WaitForChild("Datastore"));
	Encoder = require(script:WaitForChild("Encoder"));
	Entity = require(script:WaitForChild("Entity"));
	Hook = require(script:WaitForChild("Hook"));
	Inputs = require(script:WaitForChild("Inputs"));
	Instance = require(script:WaitForChild("Instance"));
	Interface = require(script:WaitForChild("Interface"));
	Math = require(script:WaitForChild("Math"));
	Network = require(script:WaitForChild("Network"));
	Patronage = require(script:WaitForChild("Patronage"));
	Table = require(script:WaitForChild("Table"));
	Time = require(script:WaitForChild("Time"));
	Vector3 = require(script:WaitForChild("Vector3"));
}