--- ### Aliases.luau
---
--- contains KeyCode-to-Alias conversions

return {
	[Enum.KeyCode.Unknown]				= " ";
	[Enum.KeyCode.One]					= "1";
	[Enum.KeyCode.Two]					= "2";
	[Enum.KeyCode.Three]				= "3";
	[Enum.KeyCode.Four]					= "4";
	[Enum.KeyCode.Five]					= "5";
	[Enum.KeyCode.Six]					= "6";
	[Enum.KeyCode.Seven]				= "7";
	[Enum.KeyCode.Eight]				= "8";
	[Enum.KeyCode.Nine]					= "9";
	[Enum.KeyCode.Zero]					= "0";
	[Enum.KeyCode.Backquote]			= "~";
	[Enum.KeyCode.LeftShift]			= "LShift";
	[Enum.KeyCode.RightShift]			= "RShift";
	[Enum.KeyCode.LeftControl]			= "LCtrl";
	[Enum.KeyCode.RightControl]			= "RCtrl";
	[Enum.KeyCode.LeftAlt]				= "LAlt";
	[Enum.KeyCode.RightAlt]				= "RAlt";
	[Enum.KeyCode.Underscore]			= "_";
	[Enum.KeyCode.Equals]				= "=";
	[Enum.KeyCode.LeftBracket]			= "[";
	[Enum.KeyCode.RightBracket]			= "]";
	[Enum.KeyCode.ButtonL1]				= "L1";
	[Enum.KeyCode.ButtonR1]				= "R1";
	[Enum.KeyCode.ButtonL2]				= "L2";
	[Enum.KeyCode.ButtonR2]				= "R2";
	[Enum.KeyCode.ButtonL3]				= "L3";
	[Enum.KeyCode.ButtonR3]				= "R3";
	[Enum.KeyCode.ButtonY]				= "Y";
	[Enum.KeyCode.ButtonX]				= "X";
	[Enum.KeyCode.ButtonB]				= "B";
	[Enum.KeyCode.ButtonA]				= "A";
}