--- ### Gamepad2DMap.luau
---
--- contains Gamepad2D-to-KeyCode conversions

return {
	["Y"] = Enum.KeyCode.ButtonY;
	["X"] = Enum.KeyCode.ButtonX;
	["B"] = Enum.KeyCode.ButtonB;
	["A"] = Enum.KeyCode.ButtonA;

	["L1"] = Enum.KeyCode.ButtonL1;
	["R1"] = Enum.KeyCode.ButtonR1;
	["L2"] = Enum.KeyCode.ButtonL2;
	["R2"] = Enum.KeyCode.ButtonR2;

	["L3"] = Enum.KeyCode.ButtonL3;
} :: {[string]: Enum.KeyCode}